FROM resin/%%RESIN_MACHINE_NAME%%-python

# Enable systemd
ENV INITSYSTEM on

# Install Python.
RUN apt-get update \
	&& apt-get install -y python \
	# Remove package lists to free up space
	&& rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt 
RUN pip install -r /requirements.txt

# install Google Maps
RUN pip install -U googlemaps

# copy current directory into /app
COPY . /app

# run python script when container lands on device
CMD ["bash", "/app/start.sh"]

